### ISSUE TITLE
some questions about Attention Module and code & data release plan

### ISSUE THREAD

**Issue by LiXinghui-666** [nyf8/AnyDesign#1]
Dear AnyDesign Authors,
Thank you for your fantastic work! And I want to ask some questions: 

1. The Q、K、V in Fashion-Guidance Attention (FGA) Module confuse me, I want to know the reason for this somewhat counterintuitive design. 
2. When will the demo or code be provided? thanks

**Comment by chinesenewton** [comment]
Thank you for your attention and feedback! This is the new version of the FGA module:
![image](https://github.com/user-attachments/assets/33f78d40-cea6-4279-8247-9c89b6cbfe47)
The code will be released soon. Thanks!

**Comment by Sheldongg** [comment]
> Thank you for your attention and feedback! This is the new version of the FGA module: ![image](https://private-user-images.githubusercontent.com/24989642/360767781-33f78d40-cea6-4279-8247-9c89b6cbfe47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDk1NjAsIm5iZiI6MTcyNjc0OTI2MCwicGF0aCI6Ii8yNDk4OTY0Mi8zNjA3Njc3ODEtMzNmNzhkNDAtY2VhNi00Mjc5LTgyNDctOWM4OWI2Y2JmZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEyMzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NTQ5ZTY3MWY0YWU5OGRmMWE1NDdjNmI2ZDBkYWFlNWMwZWNhOTFhZTUwNDU5NWY4NGIzYWZjYmM4YWI2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qJLAQEqanairLJfE92HU_rI8rBbJ2ZaK6Wirm2FoWBc) The code will be released soon. Thanks!

how do you define soon, LOL
